# 基础配置
CONFIG_FILE="config.diff"
COMMON_SH="common.sh"
ADDON_SH="addon.sh"
FREE_UP_DISK="true"
SSH_ACTIONS="false"

# 上传选项
UPLOAD_FIRMWARE_FOR_ARTIFACT="false"
UPLOAD_EFI_FIRMWARE_FOR_ARTIFACT="false"
UPLOAD_ISO_FIRMWARE_FOR_ARTIFACT="false"
UPLOAD_BIN_FIRMWARE_FOR_ARTIFACT="false"
UPLOAD_FIRMWARE_FOR_RELEASE="true"

# 自动根据 REPO_NAME 变量设置仓库（需提前设置 REPO_NAME 环境变量）
if [ "$REPO_NAME" = "lede" ]; then
    REPO_URL="https://github.com/coolsnowwolf/lede"
    REPO_BRANCH="master"

elif [ "$REPO_NAME" = "immortalwrt" ]; then
    REPO_URL="https://github.com/immortalwrt/immortalwrt.git"
    REPO_BRANCH="openwrt-24.10"

elif [ "$REPO_NAME" = "openwrt" ]; then
    REPO_URL="https://github.com/coolsnowwolf/lede"
    REPO_BRANCH="master"
fi
